## Data Frame

In [275]:
import pandas as pd

In [276]:
#list
rows=[[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]]
list_data=pd.DataFrame(rows,columns=['a','b','c'])
list_data

    a   b   c
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12
4  13  14  15

In [277]:
list_data.shape

(5, 3)

In [278]:
#Dictionary -->rows and column combination
dict_data={'Name':['Amit','Yash','Vivek'],'Money(in lakh)':[1,3,4],'Financial Stress':[1,1,0]}
a_dict=pd.DataFrame(dict_data)
a_dict

    Name  Money(in lakh)  Financial Stress
0   Amit               1                 1
1   Yash               3                 1
2  Vivek               4                 0

In [279]:
dataframe=pd.read_csv("student_depression_dataset.csv")
dataframe

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,'5-6 hours',Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,'5-6 hours',Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,'Less than 5 hours',Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,'7-8 hours',Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,'5-6 hours',Moderate,M.Tech,Yes,1.0,1.0,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27896,140685,Female,27.0,Surat,Student,5.0,0.0,5.75,5.0,0.0,'5-6 hours',Unhealthy,'Class 12',Yes,7.0,1.0,Yes,0
27897,140686,Male,27.0,Ludhiana,Student,2.0,0.0,9.40,3.0,0.0,'Less than 5 hours',Healthy,MSc,No,0.0,3.0,Yes,0
27898,140689,Male,31.0,Faridabad,Student,3.0,0.0,6.61,4.0,0.0,'5-6 hours',Unhealthy,MD,No,12.0,2.0,No,0
27899,140690,Female,18.0,Ludhiana,Student,5.0,0.0,6.88,2.0,0.0,'Less than 5 hours',Healthy,'Class 12',Yes,10.0,5.0,No,1
27900,140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,'Less than 5 hours',Healthy,BCA,Yes,2.0,3.0,Yes,1

In [280]:
type(dataframe)

pandas.DataFrame

## Data Exploration

In [281]:
dataframe

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,'5-6 hours',Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,'5-6 hours',Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,'Less than 5 hours',Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,'7-8 hours',Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,'5-6 hours',Moderate,M.Tech,Yes,1.0,1.0,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27896,140685,Female,27.0,Surat,Student,5.0,0.0,5.75,5.0,0.0,'5-6 hours',Unhealthy,'Class 12',Yes,7.0,1.0,Yes,0
27897,140686,Male,27.0,Ludhiana,Student,2.0,0.0,9.40,3.0,0.0,'Less than 5 hours',Healthy,MSc,No,0.0,3.0,Yes,0
27898,140689,Male,31.0,Faridabad,Student,3.0,0.0,6.61,4.0,0.0,'5-6 hours',Unhealthy,MD,No,12.0,2.0,No,0
27899,140690,Female,18.0,Ludhiana,Student,5.0,0.0,6.88,2.0,0.0,'Less than 5 hours',Healthy,'Class 12',Yes,10.0,5.0,No,1
27900,140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,'Less than 5 hours',Healthy,BCA,Yes,2.0,3.0,Yes,1

### Attributes

In [282]:
dataframe.shape

(27901, 18)

In [283]:
dataframe.dtypes

id                                         int64
Gender                                       str
Age                                      float64
City                                         str
Profession                                   str
Academic Pressure                        float64
Work Pressure                            float64
CGPA                                     float64
Study Satisfaction                       float64
Job Satisfaction                         float64
Sleep Duration                               str
Dietary Habits                               str
Degree                                       str
Have you ever had suicidal thoughts ?        str
Work/Study Hours                         float64
Financial Stress                             str
Family History of Mental Illness             str
Depression                                 int64
dtype: object

In [284]:
dataframe.index

RangeIndex(start=0, stop=27901, step=1)

In [285]:
dataframe.columns

Index(['id', 'Gender', 'Age', 'City', 'Profession', 'Academic Pressure',
       'Work Pressure', 'CGPA', 'Study Satisfaction', 'Job Satisfaction',
       'Sleep Duration', 'Dietary Habits', 'Degree',
       'Have you ever had suicidal thoughts ?', 'Work/Study Hours',
       'Financial Stress', 'Family History of Mental Illness', 'Depression'],
      dtype='str')

In [286]:
dataframe.values

array([[2, 'Male', 33.0, ..., '1.0', 'No', 1],
       [8, 'Female', 24.0, ..., '2.0', 'Yes', 0],
       [26, 'Male', 31.0, ..., '1.0', 'Yes', 0],
       ...,
       [140689, 'Male', 31.0, ..., '2.0', 'No', 0],
       [140690, 'Female', 18.0, ..., '5.0', 'No', 1],
       [140699, 'Male', 27.0, ..., '3.0', 'Yes', 1]],
      shape=(27901, 18), dtype=object)

In [287]:
dataframe.values[0]

array([2, 'Male', 33.0, 'Visakhapatnam', 'Student', 5.0, 0.0, 8.97, 2.0,
       0.0, "'5-6 hours'", 'Healthy', 'B.Pharm', 'Yes', 3.0, '1.0', 'No',
       1], dtype=object)

In [288]:
dataframe.ndim

2

In [289]:
dataframe.size

502218

### Functions

In [290]:
dataframe.head()

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,'5-6 hours',Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,'5-6 hours',Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,'Less than 5 hours',Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,'7-8 hours',Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,'5-6 hours',Moderate,M.Tech,Yes,1.0,1.0,No,0

In [291]:
dataframe.tail()

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
27896,140685,Female,27.0,Surat,Student,5.0,0.0,5.75,5.0,0.0,'5-6 hours',Unhealthy,'Class 12',Yes,7.0,1.0,Yes,0
27897,140686,Male,27.0,Ludhiana,Student,2.0,0.0,9.40,3.0,0.0,'Less than 5 hours',Healthy,MSc,No,0.0,3.0,Yes,0
27898,140689,Male,31.0,Faridabad,Student,3.0,0.0,6.61,4.0,0.0,'5-6 hours',Unhealthy,MD,No,12.0,2.0,No,0
27899,140690,Female,18.0,Ludhiana,Student,5.0,0.0,6.88,2.0,0.0,'Less than 5 hours',Healthy,'Class 12',Yes,10.0,5.0,No,1
27900,140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,'Less than 5 hours',Healthy,BCA,Yes,2.0,3.0,Yes,1

In [292]:
dataframe.sample(6)

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
13415,68087,Male,18.0,Ahmedabad,Student,3.0,0.0,8.64,4.0,0.0,'7-8 hours',Unhealthy,'Class 12',Yes,12.0,4.0,Yes,1
8102,40826,Female,26.0,Jaipur,Student,3.0,0.0,8.74,2.0,0.0,'More than 8 hours',Unhealthy,BCA,No,10.0,2.0,No,0
26905,135717,Female,33.0,Lucknow,Student,1.0,0.0,8.04,5.0,0.0,'More than 8 hours',Healthy,M.Com,No,6.0,4.0,Yes,0
4845,24264,Female,28.0,Bangalore,Student,5.0,0.0,5.89,5.0,0.0,'More than 8 hours',Moderate,B.Ed,Yes,6.0,2.0,No,1
3594,18050,Male,24.0,Hyderabad,Student,3.0,0.0,8.44,4.0,0.0,'Less than 5 hours',Unhealthy,B.Com,Yes,0.0,4.0,No,1
17022,86232,Male,29.0,Delhi,Student,5.0,0.0,9.42,3.0,0.0,'More than 8 hours',Unhealthy,M.Tech,No,9.0,5.0,Yes,1

In [293]:
dataframe.info()

<class 'pandas.DataFrame'>
RangeIndex: 27901 entries, 0 to 27900
Data columns (total 18 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   id                                     27901 non-null  int64
 1   Gender                                 27901 non-null  str
 2   Age                                    27901 non-null  float64
 3   City                                   27901 non-null  str
 4   Profession                             27901 non-null  str
 5   Academic Pressure                      27901 non-null  float64
 6   Work Pressure                          27901 non-null  float64
 7   CGPA                                   27901 non-null  float64
 8   Study Satisfaction                     27901 non-null  float64
 9   Job Satisfaction                       27901 non-null  float64
 10  Sleep Duration                         27901 non-null  str
 11  Dietary Habits                         27901 non-null  str
 12  Degree                                 27901 non-null  str
 13  Have you ever had suicidal thoughts ?  27901 non-null  str
 14  Work/Study Hours                       27901 non-null  float64
 15  Financial Stress                       27901 non-null  str
 16  Family History of Mental Illness       27901 non-null  str
 17  Depression                             27901 non-null  int64
dtypes: float64(7), int64(2), str(9)
memory usage: 3.8 MB

In [294]:
dataframe.describe()

,id,Age,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Work/Study Hours,Depression
count,27901.000000,27901.000000,27901.000000,27901.000000,27901.000000,27901.000000,27901.000000,27901.000000,27901.000000
mean,70442.149421,25.822300,3.141214,0.000430,7.656104,2.943837,0.000681,7.156984,0.585499
std,40641.175216,4.905687,1.381465,0.043992,1.470707,1.361148,0.044394,3.707642,0.492645
min,2.000000,18.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,35039.000000,21.000000,2.000000,0.000000,6.290000,2.000000,0.000000,4.000000,0.000000
50%,70684.000000,25.000000,3.000000,0.000000,7.770000,3.000000,0.000000,8.000000,1.000000
75%,105818.000000,30.000000,4.000000,0.000000,8.920000,4.000000,0.000000,10.000000,1.000000
max,140699.000000,59.000000,5.000000,5.000000,10.000000,5.000000,4.000000,12.000000,1.000000

## Data Cleaning

In [295]:
dataframe.isnull()

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27896,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
27897,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
27898,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
27899,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
27900,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [296]:
data=pd.read_csv("archive.csv",  compression="zip")
data.head()
type(data)

pandas.DataFrame

In [297]:
data.isnull()

,id,organization,exam_name,post,vacancies,notification_date,application_start,last_date,exam_date,application_url,notification_url,source,status,last_checked
0,False,False,False,True,True,False,True,False,False,False,False,False,False,False
1,False,False,False,True,True,False,True,False,False,False,False,False,False,False
2,False,False,False,True,True,False,True,False,False,False,False,False,False,False
3,False,False,False,True,True,False,True,False,False,False,False,False,False,False
4,False,False,False,True,True,False,True,False,False,False,False,False,False,False
5,False,False,False,True,True,False,True,False,False,False,False,False,False,False
6,False,False,False,True,True,False,True,False,False,False,False,False,False,False
7,False,False,False,True,True,False,True,False,False,False,False,False,False,False
8,False,False,False,True,True,False,True,False,False,False,False,False,False,False
9,False,False,False,True,True,False,True,False,False,False,False,False,False,False
10,False,False,False,True,True,False,True,False,False,False,False,False,False,False
11,False,False,False,True,True,False,True,False,False,False,False,False,False,False
12,False,False,False,True,True,True,True,True,True,False,False,False,False,False
13,False,False,False,True,True,True,True,True,True,False,False,False,False,False
14,False,False,False,True,True,True,True,True,True,False,False,False,False,False
15,False,False,False,True,True,True,True,True,True,False,False,False,False,False
16,False,False,False,True,True,True,True,True,True,False,False,False,False,False
17,False,False,False,True,True,True,True,True,True,False,False,False,False,False
18,False,False,False,True,True,True,True,True,True,False,False,False,False,False
19,False,False,False,True,True,True,True,True,True,False,False,False,False,False
20,False,False,False,True,True,True,True,True,True,False,False,False,False,False
21,False,False,False,True,True,True,True,True,True,False,False,False,False,False
22,False,False,False,True,True,True,True,True,True,False,False,False,False,False
23,False,False,False,True,True,True,True,True,True,False,False,False,False,False
24,False,False,False,True,True,True,True,True,True,False,False,False,False,False
25,False,False,False,True,True,True,True,True,True,False,False,False,False,False
26,False,False,False,True,True,True,True,True,True,False,False,False,False,False
27,False,False,False,True,True,True,True,True,True,False,False,False,False,False
28,False,False,False,True,True,True,True,True,True,False,False,False,False,False
29,False,False,False,True,True,True,True,True,True,False,False,False,False,False
30,False,False,False,True,True,True,True,True,True,False,False,False,False,False
31,False,False,False,True,True,True,True,True,True,False,False,False,False,False
32,False,False,False,True,True,True,True,True,True,False,False,False,False,False
33,False,False,False,True,True,True,True,True,True,False,False,False,False,False
34,False,False,False,True,True,True,True,True,True,False,False,False,False,False
35,False,False,False,True,True,True,True,True,True,False,False,False,False,False
36,False,False,False,True,True,True,True,True,True,False,False,False,False,False
37,False,False,False,True,True,True,True,True,True,False,False,False,False,False
38,False,False,False,True,True,True,True,True,True,False,False,False,False,False
39,False,False,False,True,True,True,True,True,True,False,False,False,False,False
40,False,False,False,True,True,True,True,True,True,False,False,False,False,False
41,False,False,False,True,True,True,True,True,True,False,False,False,False,False
42,False,False,False,True,True,True,True,True,True,False,False,False,False,False

In [298]:
data.isnull().sum()

id                    0
organization          0
exam_name             0
post                 43
vacancies            43
notification_date    31
application_start    43
last_date            31
exam_date            31
application_url       0
notification_url      0
source                0
status                0
last_checked          0
dtype: int64

In [299]:
data.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
dtype: bool

In [300]:
data.duplicated().sum()

np.int64(0)

In [301]:
type(data)

pandas.DataFrame

In [302]:
data.rename(columns={'notification_date':'uploading Date'},inplace=True)

In [303]:
data.rename(columns=lambda x: x.title(), inplace=True)

In [304]:
data

,Id,Organization,Exam_Name,Post,Vacancies,Uploading Date,Application_Start,Last_Date,Exam_Date,Application_Url,Notification_Url,Source,Status,Last_Checked
0,49c89ad78681cd7f,Staff Selection Commission,ASO Grade Limited Departmental Competitive Exa...,NaN,NaN,2026-03-16,NaN,2026-04-07,2026-05-01,https://ssc.gov.in,https://ssc.gov.in/api/attachment/uploads/mast...,SSC,Upcoming,2026-10-13
1,3eb35f4b4e78c1c8,Staff Selection Commission,"Combined Graduate Level Examination, 2026",NaN,NaN,2026-03-01,NaN,2026-04-01,May – June 2026,https://ssc.gov.in,https://ssc.gov.in/api/attachment/uploads/mast...,SSC,Upcoming,2026-10-13
2,937c761766e5e1ed,Staff Selection Commission,Combined Higher Secondary (10+2) Level Examina...,NaN,NaN,2026-04-01,NaN,2026-05-01,July – September 2026,https://ssc.gov.in,https://ssc.gov.in/api/attachment/uploads/mast...,SSC,Upcoming,2026-10-13
3,cb98754822e27ca7,Staff Selection Commission,"Combined Hindi Translators Examination, 2026",NaN,NaN,2026-04-01,NaN,2026-05-01,August – September 2026,https://ssc.gov.in,https://ssc.gov.in/api/attachment/uploads/mast...,SSC,Upcoming,2026-10-13
4,04e6554cb154a5f4,Staff Selection Commission,Constables (GD) in Central Armed Police Forces...,NaN,NaN,2026-09-01,NaN,2026-10-01,January – March 2027,https://ssc.gov.in,https://ssc.gov.in/api/attachment/uploads/mast...,SSC,Upcoming,2026-10-13
5,db494908cd669c36,Staff Selection Commission,JSA / LDC Grade Limited Departmental Competiti...,NaN,NaN,2026-03-16,NaN,2026-04-07,2026-05-01,https://ssc.gov.in,https://ssc.gov.in/api/attachment/uploads/mast...,SSC,Upcoming,2026-10-13
6,d78f59d98c7470d5,Staff Selection Commission,"Junior Engineer (Civil, Mechanical & Electrica...",NaN,NaN,2026-03-01,NaN,2026-04-01,May – June 2026,https://ssc.gov.in,https://ssc.gov.in/api/attachment/uploads/mast...,SSC,Upcoming,2026-10-13
7,c107e5d84244f9cb,Staff Selection Commission,Multi-Tasking (Non- Technical) Staff & Havalda...,NaN,NaN,2026-06-01,NaN,2026-07-01,September – November 2026,https://ssc.gov.in,https://ssc.gov.in/api/attachment/uploads/mast...,SSC,Upcoming,2026-10-13
8,e7a401a7cbea608b,Staff Selection Commission,SSA / UDC Grade Limited Departmental Competiti...,NaN,NaN,2026-03-16,NaN,2026-04-07,2026-05-01,https://ssc.gov.in,https://ssc.gov.in/api/attachment/uploads/mast...,SSC,Upcoming,2026-10-13
9,d328f97a059fb443,Staff Selection Commission,"Selection Post Examination, Phase-XIV, 2026",NaN,NaN,2026-03-01,NaN,2026-04-01,May – July 2026,https://ssc.gov.in,https://ssc.gov.in/api/attachment/uploads/mast...,SSC,Upcoming,2026-10-13
10,bb7d9cbb0fcc77c6,Staff Selection Commission,"Stenographer Grade ‘C’ & ‘D’ Examination, 2026",NaN,NaN,2026-04-01,NaN,2026-05-01,August – September 2026,https://ssc.gov.in,https://ssc.gov.in/api/attachment/uploads/mast...,SSC,Upcoming,2026-10-13
11,338ee7f7b6f96e4b,Staff Selection Commission,Sub-Inspector in Delhi Police & Central Armed ...,NaN,NaN,2026-05-01,NaN,2026-06-01,October – November 2026,https://ssc.gov.in,https://ssc.gov.in/api/attachment/uploads/mast...,SSC,Upcoming,2026-10-13
12,23709ed0cfc9d20c,Union Public Service Commission,Date / (s) of Examination,NaN,NaN,NaN,NaN,NaN,NaN,https://upsconline.nic.in,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
13,ba19835a6d9f08b6,Union Public Service Commission,Duration of Examination,NaN,NaN,NaN,NaN,NaN,NaN,https://upsconline.nic.in,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
14,600a5f5ac5cb10c7,Union Public Service Commission,Examination,NaN,NaN,NaN,NaN,NaN,NaN,https://upsconline.nic.in,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
15,a16426271ecd5e82,Union Public Service Commission,Forthcoming Examinations,NaN,NaN,NaN,NaN,NaN,NaN,https://upsconline.nic.in,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
16,f1fcda26666e5308,Union Public Service Commission,Name of Examination,NaN,NaN,NaN,NaN,NaN,NaN,https://upsconline.nic.in,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
17,0ba79e68256911eb,Union Public Service Commission,Name of Examination: CISF AC(EXE) LDCE-2025,NaN,NaN,NaN,NaN,NaN,NaN,https://upsconline.nic.in,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
18,212bdecc1aa07509,Union Public Service Commission,Name of Examination: CISF AC(EXE) LDCE-2026,NaN,NaN,NaN,NaN,NaN,NaN,https://upsconline.nic.in,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
19,71f0ad9a6d1089ae,Union Public Service Commission,Name of Examination: Central Armed Police Forc...,NaN,NaN,NaN,NaN,NaN,NaN,https://upsconline.nic.in,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
20,c08a4a563ddf6781,Union Public Service Commission,Name of Examination: Central Armed Police Forc...,NaN,NaN,NaN,NaN,NaN,NaN,https://upsconline.nic.in,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
21,4d368dd857cf6b2d,Union Public Service Commission,Name of Examination: Civil Services (Prelimina...,NaN,NaN,NaN,NaN,NaN,NaN,https://upsconline.nic.in,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
22,2a87784a63181542,Union Public Service Commission,Name of Examination: Civil Services (Prelimina...,NaN,NaN,NaN,NaN,NaN,NaN,https://upsconline.nic.in,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
23,dcad90eb1cbb161a,Union Public Service Commission,Name of Examination: Combined Defence Services...,NaN,NaN,NaN,NaN,NaN,NaN,https://upsconline.nic.in,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
24,77e5181f5373b2af,Union Public Service Commission,Name of Examination: Combined Defence Services...,NaN,NaN,NaN,NaN,NaN,NaN,https://upsconline.nic.in,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
25,6b66a7c97b27a248,Union Public Service Commission,Name of Examination: Combined Defence Services...,NaN,NaN,NaN,NaN,NaN,NaN,https://upsconline.nic.in,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
26,aa40f87dc37c5c52,Union Public Service Commission,Name of Examination: Combined Defence Services...,NaN,NaN,NaN,NaN,NaN,NaN,https://upsconline.nic.in,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
27,5654625112a1f003,Union Public Service Commission,Name of Examination: Combined Geo-Scientist (P...,NaN,NaN,NaN,NaN,NaN,NaN,https://upsconline.nic.in,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
28,57cdf7ddd7a942cc,Union Public Service Commission,Name of Examination: Combined Geo-Scientist (P...,NaN,NaN,NaN,NaN,NaN,NaN,https://upsconline.nic.in,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
29,2ebe86f0a99b1c25,Union Public Service Commission,Name of Examination: Combined Medical Services...,NaN,NaN,NaN,NaN,NaN,NaN,https://upsconline.nic.in,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
30,c8aa2a0a3be0ac7c,Union Public Service Commission,Name of Examination: Combined Medical Services...,NaN,NaN,NaN,NaN,NaN,NaN,https://upsconline.nic.in,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
31,f06b58d3bf303f1e,Union Public Service Commission,Name of Examination: Combined Section Officer ...,NaN,NaN,NaN,NaN,NaN,NaN,https://upsconline.nic.in,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
32,3701a2c45237153c,Union Public Service Commission,Name of Examination: Combined Section Officers...,NaN,NaN,NaN,NaN,NaN,NaN,https://upsconline.nic.in,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
33,973c81118e32e7d1,Union Public Service Commission,Name of Examination: Engineering Services (Pre...,NaN,NaN,NaN,NaN,NaN,NaN,https://upsconline.nic.in,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
34,f84151086c505af2,Union Public Service Commission,Name of Examination: Engineering Services (Pre...,NaN,NaN,NaN,NaN,NaN,NaN,https://upsconline.nic.in,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
35,e31bb557da19be3a,Union Public Service Commission,Name of Examination: Indian Economic Service -...,NaN,NaN,NaN,NaN,NaN,NaN,https://upsconline.nic.in,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
36,5bc094a218de5f9c,Union Public Service Commission,Name of Examination: Indian Economic Service -...,NaN,NaN,NaN,NaN,NaN,NaN,https://upsconline.nic.in,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
37,0c45f4f8ded02d47,Union Public Service Commission,Name of Examination: Indian Forest Service (Pr...,NaN,NaN,NaN,NaN,NaN,NaN,https://upsconline.nic.in,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
38,353d74d3b8eebe66,Union Public Service Commission,Name of Examination: Indian Forest Service (Pr...,NaN,NaN,NaN,NaN,NaN,NaN,https://upsconline.nic.in,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
39,26c2e296070079f6,Union Public Service Commission,Name of Examination: National Defence Academy ...,NaN,NaN,NaN,NaN,NaN,NaN,https://upsconline.nic.in,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
40,641da92514dabcb9,Union Public Service Commission,Name of Examination: National Defence Academy ...,NaN,NaN,NaN,NaN,NaN,NaN,https://upsconline.nic.in,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
41,2cf5fdf3defabc1d,Union Public Service Commission,Name of Examination: National Defence Academy ...,NaN,NaN,NaN,NaN,NaN,NaN,https://upsconline.nic.in,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
42,7241f7cedfba8318,Union Public Service Commission,Name of Examination: National Defence Academy ...,NaN,NaN,NaN,NaN,NaN,NaN,https://upsconline.nic.in,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13

In [305]:
data.max()

Id                                                    f84151086c505af2
Organization                           Union Public Service Commission
Exam_Name            Sub-Inspector in Delhi Police & Central Armed ...
Post                                                               NaN
Vacancies                                                          NaN
Uploading Date                                              2026-09-01
Application_Start                                                  NaN
Last_Date                                                   2026-10-01
Exam_Date                                    September – November 2026
Application_Url                              https://upsconline.nic.in
Notification_Url     https://www.upsc.gov.in/exams-related-info/exa...
Source                                                            UPSC
Status                                                        Upcoming
Last_Checked                                                2026-10-13
dtype: object

In [306]:
data.min()

Id                                                    04e6554cb154a5f4
Organization                                Staff Selection Commission
Exam_Name            ASO Grade Limited Departmental Competitive Exa...
Post                                                               NaN
Vacancies                                                          NaN
Uploading Date                                              2026-03-01
Application_Start                                                  NaN
Last_Date                                                   2026-04-01
Exam_Date                                                   2026-05-01
Application_Url                                     https://ssc.gov.in
Notification_Url     https://ssc.gov.in/api/attachment/uploads/mast...
Source                                                             SSC
Status                                                       Published
Last_Checked                                                2026-10-13
dtype: object

In [307]:
dataframe

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,'5-6 hours',Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,'5-6 hours',Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,'Less than 5 hours',Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,'7-8 hours',Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,'5-6 hours',Moderate,M.Tech,Yes,1.0,1.0,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27896,140685,Female,27.0,Surat,Student,5.0,0.0,5.75,5.0,0.0,'5-6 hours',Unhealthy,'Class 12',Yes,7.0,1.0,Yes,0
27897,140686,Male,27.0,Ludhiana,Student,2.0,0.0,9.40,3.0,0.0,'Less than 5 hours',Healthy,MSc,No,0.0,3.0,Yes,0
27898,140689,Male,31.0,Faridabad,Student,3.0,0.0,6.61,4.0,0.0,'5-6 hours',Unhealthy,MD,No,12.0,2.0,No,0
27899,140690,Female,18.0,Ludhiana,Student,5.0,0.0,6.88,2.0,0.0,'Less than 5 hours',Healthy,'Class 12',Yes,10.0,5.0,No,1
27900,140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,'Less than 5 hours',Healthy,BCA,Yes,2.0,3.0,Yes,1

In [308]:
dataframe.min()

id                                                      2
Gender                                             Female
Age                                                  18.0
City                                         'Less Delhi'
Profession                               'Civil Engineer'
Academic Pressure                                     0.0
Work Pressure                                         0.0
CGPA                                                  0.0
Study Satisfaction                                    0.0
Job Satisfaction                                      0.0
Sleep Duration                                '5-6 hours'
Dietary Habits                                    Healthy
Degree                                         'Class 12'
Have you ever had suicidal thoughts ?                  No
Work/Study Hours                                      0.0
Financial Stress                                      1.0
Family History of Mental Illness                       No
Depression                                              0
dtype: object

In [309]:
dataframe.sum()

id                                                                              1965406411
Gender                                   MaleFemaleMaleFemaleFemaleMaleMaleFemaleMaleMa...
Age                                                                               720468.0
City                                     VisakhapatnamBangaloreSrinagarVaranasiJaipurPu...
Profession                               StudentStudentStudentStudentStudentStudentStud...
Academic Pressure                                                                  87643.0
Work Pressure                                                                         12.0
CGPA                                                                           213612.9625
Study Satisfaction                                                                 82136.0
Job Satisfaction                                                                      19.0
Sleep Duration                           '5-6 hours''5-6 hours''Less than 5 hours''7-8 ...
Dietary Habits                           HealthyModerateHealthyModerateModerateHealthyH...
Degree                                   B.PharmBScBABCAM.TechPhDBSc'Class 12'B.EdLLB'C...
Have you ever had suicidal thoughts ?    YesNoNoYesYesNoNoNoYesYesYesYesNoNoYesYesYesYe...
Work/Study Hours                                                                  199687.0
Financial Stress                         1.02.01.05.01.01.02.01.03.05.01.02.01.02.05.02...
Family History of Mental Illness         NoYesYesYesNoNoNoYesNoNoYesYesYesYesYesYesYesN...
Depression                                                                           16336
dtype: object

In [310]:
dataframe.max()

id                                              140699
Gender                                            Male
Age                                               59.0
City                                     Visakhapatnam
Profession                                     Teacher
Academic Pressure                                  5.0
Work Pressure                                      5.0
CGPA                                              10.0
Study Satisfaction                                 5.0
Job Satisfaction                                   4.0
Sleep Duration                                  Others
Dietary Habits                               Unhealthy
Degree                                             PhD
Have you ever had suicidal thoughts ?              Yes
Work/Study Hours                                  12.0
Financial Stress                                     ?
Family History of Mental Illness                   Yes
Depression                                           1
dtype: object

In [311]:
dataframe.sum(axis=0)

id                                                                              1965406411
Gender                                   MaleFemaleMaleFemaleFemaleMaleMaleFemaleMaleMa...
Age                                                                               720468.0
City                                     VisakhapatnamBangaloreSrinagarVaranasiJaipurPu...
Profession                               StudentStudentStudentStudentStudentStudentStud...
Academic Pressure                                                                  87643.0
Work Pressure                                                                         12.0
CGPA                                                                           213612.9625
Study Satisfaction                                                                 82136.0
Job Satisfaction                                                                      19.0
Sleep Duration                           '5-6 hours''5-6 hours''Less than 5 hours''7-8 ...
Dietary Habits                           HealthyModerateHealthyModerateModerateHealthyH...
Degree                                   B.PharmBScBABCAM.TechPhDBSc'Class 12'B.EdLLB'C...
Have you ever had suicidal thoughts ?    YesNoNoYesYesNoNoNoYesYesYesYesNoNoYesYesYesYe...
Work/Study Hours                                                                  199687.0
Financial Stress                         1.02.01.05.01.01.02.01.03.05.01.02.01.02.05.02...
Family History of Mental Illness         NoYesYesYesNoNoNoYesNoNoYesYesYesYesYesYesYesN...
Depression                                                                           16336
dtype: object

In [312]:
dataframe.sample()

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
13320,67590,Female,34.0,Rajkot,Student,3.0,0.0,8.07,5.0,0.0,'Less than 5 hours',Moderate,BE,Yes,5.0,3.0,No,1

In [313]:

type(dataframe['Academic Pressure'])

pandas.Series

In [314]:
dataframe['Academic Pressure'].sum()

np.float64(87643.0)

In [315]:
dataframe.columns

Index(['id', 'Gender', 'Age', 'City', 'Profession', 'Academic Pressure',
       'Work Pressure', 'CGPA', 'Study Satisfaction', 'Job Satisfaction',
       'Sleep Duration', 'Dietary Habits', 'Degree',
       'Have you ever had suicidal thoughts ?', 'Work/Study Hours',
       'Financial Stress', 'Family History of Mental Illness', 'Depression'],
      dtype='str')

In [316]:
dataframe[['Age','Sleep Duration','CGPA','Depression']]

        Age       Sleep Duration  CGPA  Depression
0      33.0          '5-6 hours'  8.97           1
1      24.0          '5-6 hours'  5.90           0
2      31.0  'Less than 5 hours'  7.03           0
3      28.0          '7-8 hours'  5.59           1
4      25.0          '5-6 hours'  8.13           0
...     ...                  ...   ...         ...
27896  27.0          '5-6 hours'  5.75           0
27897  27.0  'Less than 5 hours'  9.40           0
27898  31.0          '5-6 hours'  6.61           0
27899  18.0  'Less than 5 hours'  6.88           1
27900  27.0  'Less than 5 hours'  9.24           1

[27901 rows x 4 columns]

In [317]:
dataframe.head(2)

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,'5-6 hours',Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,'5-6 hours',Moderate,BSc,No,3.0,2.0,Yes,0

In [318]:
dataframe.iloc[1000]

id                                                5152
Gender                                            Male
Age                                               29.0
City                                     Visakhapatnam
Profession                                     Student
Academic Pressure                                  3.0
Work Pressure                                      0.0
CGPA                                              7.94
Study Satisfaction                                 3.0
Job Satisfaction                                   0.0
Sleep Duration                             '5-6 hours'
Dietary Habits                                Moderate
Degree                                             BSc
Have you ever had suicidal thoughts ?               No
Work/Study Hours                                   2.0
Financial Stress                                   1.0
Family History of Mental Illness                   Yes
Depression                                           0
Name: 1000, dtype: object

In [319]:
dataframe.iloc[2:10]

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,'Less than 5 hours',Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,'7-8 hours',Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,'5-6 hours',Moderate,M.Tech,Yes,1.0,1.0,No,0
5,33,Male,29.0,Pune,Student,2.0,0.0,5.70,3.0,0.0,'Less than 5 hours',Healthy,PhD,No,4.0,1.0,No,0
6,52,Male,30.0,Thane,Student,3.0,0.0,9.54,4.0,0.0,'7-8 hours',Healthy,BSc,No,1.0,2.0,No,0
7,56,Female,30.0,Chennai,Student,2.0,0.0,8.04,4.0,0.0,'Less than 5 hours',Unhealthy,'Class 12',No,0.0,1.0,Yes,0
8,59,Male,28.0,Nagpur,Student,3.0,0.0,9.79,1.0,0.0,'7-8 hours',Moderate,B.Ed,Yes,12.0,3.0,No,1
9,62,Male,31.0,Nashik,Student,2.0,0.0,8.38,3.0,0.0,'Less than 5 hours',Moderate,LLB,Yes,2.0,5.0,No,1

In [320]:
dataframe.iloc[::2]

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,'5-6 hours',Healthy,B.Pharm,Yes,3.0,1.0,No,1
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,'Less than 5 hours',Healthy,BA,No,9.0,1.0,Yes,0
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,'5-6 hours',Moderate,M.Tech,Yes,1.0,1.0,No,0
6,52,Male,30.0,Thane,Student,3.0,0.0,9.54,4.0,0.0,'7-8 hours',Healthy,BSc,No,1.0,2.0,No,0
8,59,Male,28.0,Nagpur,Student,3.0,0.0,9.79,1.0,0.0,'7-8 hours',Moderate,B.Ed,Yes,12.0,3.0,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27892,140669,Female,20.0,Indore,Student,3.0,0.0,7.72,5.0,0.0,'Less than 5 hours',Moderate,'Class 12',Yes,8.0,1.0,No,0
27894,140681,Male,23.0,Srinagar,Student,3.0,0.0,6.00,2.0,0.0,'More than 8 hours',Healthy,MBBS,Yes,12.0,4.0,No,0
27896,140685,Female,27.0,Surat,Student,5.0,0.0,5.75,5.0,0.0,'5-6 hours',Unhealthy,'Class 12',Yes,7.0,1.0,Yes,0
27898,140689,Male,31.0,Faridabad,Student,3.0,0.0,6.61,4.0,0.0,'5-6 hours',Unhealthy,MD,No,12.0,2.0,No,0
27900,140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,'Less than 5 hours',Healthy,BCA,Yes,2.0,3.0,Yes,1

In [321]:
dataframe

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,'5-6 hours',Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,'5-6 hours',Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,'Less than 5 hours',Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,'7-8 hours',Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,'5-6 hours',Moderate,M.Tech,Yes,1.0,1.0,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27896,140685,Female,27.0,Surat,Student,5.0,0.0,5.75,5.0,0.0,'5-6 hours',Unhealthy,'Class 12',Yes,7.0,1.0,Yes,0
27897,140686,Male,27.0,Ludhiana,Student,2.0,0.0,9.40,3.0,0.0,'Less than 5 hours',Healthy,MSc,No,0.0,3.0,Yes,0
27898,140689,Male,31.0,Faridabad,Student,3.0,0.0,6.61,4.0,0.0,'5-6 hours',Unhealthy,MD,No,12.0,2.0,No,0
27899,140690,Female,18.0,Ludhiana,Student,5.0,0.0,6.88,2.0,0.0,'Less than 5 hours',Healthy,'Class 12',Yes,10.0,5.0,No,1
27900,140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,'Less than 5 hours',Healthy,BCA,Yes,2.0,3.0,Yes,1

In [322]:
dataframe=dataframe.set_index('City')

In [323]:
dataframe

,id,Gender,Age,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
City,,,,,,,,,,,,,,,,,
Visakhapatnam,2,Male,33.0,Student,5.0,0.0,8.97,2.0,0.0,'5-6 hours',Healthy,B.Pharm,Yes,3.0,1.0,No,1
Bangalore,8,Female,24.0,Student,2.0,0.0,5.90,5.0,0.0,'5-6 hours',Moderate,BSc,No,3.0,2.0,Yes,0
Srinagar,26,Male,31.0,Student,3.0,0.0,7.03,5.0,0.0,'Less than 5 hours',Healthy,BA,No,9.0,1.0,Yes,0
Varanasi,30,Female,28.0,Student,3.0,0.0,5.59,2.0,0.0,'7-8 hours',Moderate,BCA,Yes,4.0,5.0,Yes,1
Jaipur,32,Female,25.0,Student,4.0,0.0,8.13,3.0,0.0,'5-6 hours',Moderate,M.Tech,Yes,1.0,1.0,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Surat,140685,Female,27.0,Student,5.0,0.0,5.75,5.0,0.0,'5-6 hours',Unhealthy,'Class 12',Yes,7.0,1.0,Yes,0
Ludhiana,140686,Male,27.0,Student,2.0,0.0,9.40,3.0,0.0,'Less than 5 hours',Healthy,MSc,No,0.0,3.0,Yes,0
Faridabad,140689,Male,31.0,Student,3.0,0.0,6.61,4.0,0.0,'5-6 hours',Unhealthy,MD,No,12.0,2.0,No,0
Ludhiana,140690,Female,18.0,Student,5.0,0.0,6.88,2.0,0.0,'Less than 5 hours',Healthy,'Class 12',Yes,10.0,5.0,No,1
Patna,140699,Male,27.0,Student,4.0,0.0,9.24,1.0,0.0,'Less than 5 hours',Healthy,BCA,Yes,2.0,3.0,Yes,1

In [324]:
dataframe.loc['Patna']

,id,Gender,Age,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
City,,,,,,,,,,,,,,,,,
Patna,420,Male,32.0,Student,3.0,0.0,9.11,5.0,0.0,'7-8 hours',Moderate,MBBS,Yes,5.0,5.0,Yes,1
Patna,580,Male,21.0,Student,1.0,0.0,8.50,3.0,0.0,'5-6 hours',Healthy,BCA,Yes,10.0,3.0,Yes,1
Patna,714,Female,29.0,Student,3.0,0.0,8.75,5.0,0.0,'7-8 hours',Moderate,BCA,No,10.0,5.0,No,1
Patna,750,Male,21.0,Student,4.0,0.0,5.76,1.0,0.0,'Less than 5 hours',Unhealthy,B.Ed,Yes,9.0,4.0,Yes,1
Patna,821,Female,21.0,Student,5.0,0.0,5.75,1.0,0.0,'7-8 hours',Healthy,MBBS,Yes,11.0,4.0,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Patna,139944,Female,28.0,Student,3.0,0.0,9.46,4.0,0.0,'Less than 5 hours',Moderate,B.Ed,Yes,7.0,4.0,No,1
Patna,140033,Male,31.0,Student,3.0,0.0,5.11,1.0,0.0,'Less than 5 hours',Moderate,B.Tech,Yes,11.0,5.0,Yes,1
Patna,140083,Male,19.0,Student,1.0,0.0,6.73,2.0,0.0,'Less than 5 hours',Unhealthy,'Class 12',Yes,12.0,3.0,Yes,1
Patna,140199,Male,31.0,Student,5.0,0.0,6.53,1.0,0.0,'More than 8 hours',Unhealthy,'Class 12',Yes,10.0,5.0,No,1
Patna,140699,Male,27.0,Student,4.0,0.0,9.24,1.0,0.0,'Less than 5 hours',Healthy,BCA,Yes,2.0,3.0,Yes,1

In [325]:
dataframe.iloc[[1,2000,3000,3001]]

,id,Gender,Age,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
City,,,,,,,,,,,,,,,,,
Bangalore,8,Female,24.0,Student,2.0,0.0,5.90,5.0,0.0,'5-6 hours',Moderate,BSc,No,3.0,2.0,Yes,0
Patna,10255,Male,25.0,Student,3.0,0.0,7.49,5.0,0.0,'Less than 5 hours',Healthy,B.Tech,Yes,10.0,1.0,No,1
Kolkata,15184,Male,33.0,Student,3.0,0.0,6.38,3.0,0.0,'More than 8 hours',Unhealthy,MSc,No,11.0,1.0,Yes,0
Meerut,15186,Male,19.0,Student,4.0,0.0,8.17,1.0,0.0,'7-8 hours',Moderate,'Class 12',Yes,7.0,3.0,Yes,1

In [326]:
dataframe.loc[['Patna','Kolkata']]

,id,Gender,Age,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
City,,,,,,,,,,,,,,,,,
Patna,420,Male,32.0,Student,3.0,0.0,9.11,5.0,0.0,'7-8 hours',Moderate,MBBS,Yes,5.0,5.0,Yes,1
Patna,580,Male,21.0,Student,1.0,0.0,8.50,3.0,0.0,'5-6 hours',Healthy,BCA,Yes,10.0,3.0,Yes,1
Patna,714,Female,29.0,Student,3.0,0.0,8.75,5.0,0.0,'7-8 hours',Moderate,BCA,No,10.0,5.0,No,1
Patna,750,Male,21.0,Student,4.0,0.0,5.76,1.0,0.0,'Less than 5 hours',Unhealthy,B.Ed,Yes,9.0,4.0,Yes,1
Patna,821,Female,21.0,Student,5.0,0.0,5.75,1.0,0.0,'7-8 hours',Healthy,MBBS,Yes,11.0,4.0,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Kolkata,139679,Female,33.0,Student,3.0,0.0,8.90,5.0,0.0,'Less than 5 hours',Moderate,M.Pharm,Yes,5.0,5.0,No,0
Kolkata,140161,Male,22.0,Student,3.0,0.0,8.73,2.0,0.0,'Less than 5 hours',Healthy,B.Com,Yes,6.0,5.0,Yes,1
Kolkata,140270,Female,33.0,Student,1.0,0.0,7.09,1.0,0.0,'More than 8 hours',Healthy,LLM,Yes,5.0,4.0,No,0
Kolkata,140316,Male,21.0,Student,1.0,0.0,9.71,5.0,0.0,'5-6 hours',Moderate,MSc,No,9.0,2.0,No,0
Kolkata,140630,Male,19.0,Student,4.0,0.0,7.13,1.0,0.0,'More than 8 hours',Moderate,'Class 12',No,10.0,2.0,No,1

In [338]:
dataframe.iloc[0:6][['Age', 'CGPA', 'Degree']]

                Age  CGPA   Degree
City
Visakhapatnam  33.0  8.97  B.Pharm
Bangalore      24.0  5.90      BSc
Srinagar       31.0  7.03       BA
Varanasi       28.0  5.59      BCA
Jaipur         25.0  8.13   M.Tech
Pune           29.0  5.70      PhD