# Goverment Exam Data filtering

In [48]:
import pandas as pd 
df=pd.read_csv("archive.csv",compression="zip")
df

,id,organization,exam_name,post,vacancies,notification_date,application_start,last_date,exam_date,application_url,notification_url,source,status,last_checked
0,49c89ad78681cd7f,Staff Selection Commission,ASO Grade Limited Departmental Competitive Exa...,NaN,NaN,2026-03-16,NaN,2026-04-07,2026-05-01,https://ssc.gov.in,https://ssc.gov.in/api/attachment/uploads/mast...,SSC,Upcoming,2026-10-13
1,3eb35f4b4e78c1c8,Staff Selection Commission,"Combined Graduate Level Examination, 2026",NaN,NaN,2026-03-01,NaN,2026-04-01,May – June 2026,https://ssc.gov.in,https://ssc.gov.in/api/attachment/uploads/mast...,SSC,Upcoming,2026-10-13
2,937c761766e5e1ed,Staff Selection Commission,Combined Higher Secondary (10+2) Level Examina...,NaN,NaN,2026-04-01,NaN,2026-05-01,July – September 2026,https://ssc.gov.in,https://ssc.gov.in/api/attachment/uploads/mast...,SSC,Upcoming,2026-10-13
3,cb98754822e27ca7,Staff Selection Commission,"Combined Hindi Translators Examination, 2026",NaN,NaN,2026-04-01,NaN,2026-05-01,August – September 2026,https://ssc.gov.in,https://ssc.gov.in/api/attachment/uploads/mast...,SSC,Upcoming,2026-10-13
4,04e6554cb154a5f4,Staff Selection Commission,Constables (GD) in Central Armed Police Forces...,NaN,NaN,2026-09-01,NaN,2026-10-01,January – March 2027,https://ssc.gov.in,https://ssc.gov.in/api/attachment/uploads/mast...,SSC,Upcoming,2026-10-13
5,db494908cd669c36,Staff Selection Commission,JSA / LDC Grade Limited Departmental Competiti...,NaN,NaN,2026-03-16,NaN,2026-04-07,2026-05-01,https://ssc.gov.in,https://ssc.gov.in/api/attachment/uploads/mast...,SSC,Upcoming,2026-10-13
6,d78f59d98c7470d5,Staff Selection Commission,"Junior Engineer (Civil, Mechanical & Electrica...",NaN,NaN,2026-03-01,NaN,2026-04-01,May – June 2026,https://ssc.gov.in,https://ssc.gov.in/api/attachment/uploads/mast...,SSC,Upcoming,2026-10-13
7,c107e5d84244f9cb,Staff Selection Commission,Multi-Tasking (Non- Technical) Staff & Havalda...,NaN,NaN,2026-06-01,NaN,2026-07-01,September – November 2026,https://ssc.gov.in,https://ssc.gov.in/api/attachment/uploads/mast...,SSC,Upcoming,2026-10-13
8,e7a401a7cbea608b,Staff Selection Commission,SSA / UDC Grade Limited Departmental Competiti...,NaN,NaN,2026-03-16,NaN,2026-04-07,2026-05-01,https://ssc.gov.in,https://ssc.gov.in/api/attachment/uploads/mast...,SSC,Upcoming,2026-10-13
9,d328f97a059fb443,Staff Selection Commission,"Selection Post Examination, Phase-XIV, 2026",NaN,NaN,2026-03-01,NaN,2026-04-01,May – July 2026,https://ssc.gov.in,https://ssc.gov.in/api/attachment/uploads/mast...,SSC,Upcoming,2026-10-13
10,bb7d9cbb0fcc77c6,Staff Selection Commission,"Stenographer Grade ‘C’ & ‘D’ Examination, 2026",NaN,NaN,2026-04-01,NaN,2026-05-01,August – September 2026,https://ssc.gov.in,https://ssc.gov.in/api/attachment/uploads/mast...,SSC,Upcoming,2026-10-13
11,338ee7f7b6f96e4b,Staff Selection Commission,Sub-Inspector in Delhi Police & Central Armed ...,NaN,NaN,2026-05-01,NaN,2026-06-01,October – November 2026,https://ssc.gov.in,https://ssc.gov.in/api/attachment/uploads/mast...,SSC,Upcoming,2026-10-13
12,23709ed0cfc9d20c,Union Public Service Commission,Date / (s) of Examination,NaN,NaN,NaN,NaN,NaN,NaN,https://upsconline.nic.in,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
13,ba19835a6d9f08b6,Union Public Service Commission,Duration of Examination,NaN,NaN,NaN,NaN,NaN,NaN,https://upsconline.nic.in,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
14,600a5f5ac5cb10c7,Union Public Service Commission,Examination,NaN,NaN,NaN,NaN,NaN,NaN,https://upsconline.nic.in,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
15,a16426271ecd5e82,Union Public Service Commission,Forthcoming Examinations,NaN,NaN,NaN,NaN,NaN,NaN,https://upsconline.nic.in,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
16,f1fcda26666e5308,Union Public Service Commission,Name of Examination,NaN,NaN,NaN,NaN,NaN,NaN,https://upsconline.nic.in,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
17,0ba79e68256911eb,Union Public Service Commission,Name of Examination: CISF AC(EXE) LDCE-2025,NaN,NaN,NaN,NaN,NaN,NaN,https://upsconline.nic.in,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
18,212bdecc1aa07509,Union Public Service Commission,Name of Examination: CISF AC(EXE) LDCE-2026,NaN,NaN,NaN,NaN,NaN,NaN,https://upsconline.nic.in,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
19,71f0ad9a6d1089ae,Union Public Service Commission,Name of Examination: Central Armed Police Forc...,NaN,NaN,NaN,NaN,NaN,NaN,https://upsconline.nic.in,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
20,c08a4a563ddf6781,Union Public Service Commission,Name of Examination: Central Armed Police Forc...,NaN,NaN,NaN,NaN,NaN,NaN,https://upsconline.nic.in,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
21,4d368dd857cf6b2d,Union Public Service Commission,Name of Examination: Civil Services (Prelimina...,NaN,NaN,NaN,NaN,NaN,NaN,https://upsconline.nic.in,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
22,2a87784a63181542,Union Public Service Commission,Name of Examination: Civil Services (Prelimina...,NaN,NaN,NaN,NaN,NaN,NaN,https://upsconline.nic.in,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
23,dcad90eb1cbb161a,Union Public Service Commission,Name of Examination: Combined Defence Services...,NaN,NaN,NaN,NaN,NaN,NaN,https://upsconline.nic.in,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
24,77e5181f5373b2af,Union Public Service Commission,Name of Examination: Combined Defence Services...,NaN,NaN,NaN,NaN,NaN,NaN,https://upsconline.nic.in,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
25,6b66a7c97b27a248,Union Public Service Commission,Name of Examination: Combined Defence Services...,NaN,NaN,NaN,NaN,NaN,NaN,https://upsconline.nic.in,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
26,aa40f87dc37c5c52,Union Public Service Commission,Name of Examination: Combined Defence Services...,NaN,NaN,NaN,NaN,NaN,NaN,https://upsconline.nic.in,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
27,5654625112a1f003,Union Public Service Commission,Name of Examination: Combined Geo-Scientist (P...,NaN,NaN,NaN,NaN,NaN,NaN,https://upsconline.nic.in,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
28,57cdf7ddd7a942cc,Union Public Service Commission,Name of Examination: Combined Geo-Scientist (P...,NaN,NaN,NaN,NaN,NaN,NaN,https://upsconline.nic.in,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
29,2ebe86f0a99b1c25,Union Public Service Commission,Name of Examination: Combined Medical Services...,NaN,NaN,NaN,NaN,NaN,NaN,https://upsconline.nic.in,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
30,c8aa2a0a3be0ac7c,Union Public Service Commission,Name of Examination: Combined Medical Services...,NaN,NaN,NaN,NaN,NaN,NaN,https://upsconline.nic.in,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
31,f06b58d3bf303f1e,Union Public Service Commission,Name of Examination: Combined Section Officer ...,NaN,NaN,NaN,NaN,NaN,NaN,https://upsconline.nic.in,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
32,3701a2c45237153c,Union Public Service Commission,Name of Examination: Combined Section Officers...,NaN,NaN,NaN,NaN,NaN,NaN,https://upsconline.nic.in,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
33,973c81118e32e7d1,Union Public Service Commission,Name of Examination: Engineering Services (Pre...,NaN,NaN,NaN,NaN,NaN,NaN,https://upsconline.nic.in,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
34,f84151086c505af2,Union Public Service Commission,Name of Examination: Engineering Services (Pre...,NaN,NaN,NaN,NaN,NaN,NaN,https://upsconline.nic.in,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
35,e31bb557da19be3a,Union Public Service Commission,Name of Examination: Indian Economic Service -...,NaN,NaN,NaN,NaN,NaN,NaN,https://upsconline.nic.in,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
36,5bc094a218de5f9c,Union Public Service Commission,Name of Examination: Indian Economic Service -...,NaN,NaN,NaN,NaN,NaN,NaN,https://upsconline.nic.in,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
37,0c45f4f8ded02d47,Union Public Service Commission,Name of Examination: Indian Forest Service (Pr...,NaN,NaN,NaN,NaN,NaN,NaN,https://upsconline.nic.in,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
38,353d74d3b8eebe66,Union Public Service Commission,Name of Examination: Indian Forest Service (Pr...,NaN,NaN,NaN,NaN,NaN,NaN,https://upsconline.nic.in,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
39,26c2e296070079f6,Union Public Service Commission,Name of Examination: National Defence Academy ...,NaN,NaN,NaN,NaN,NaN,NaN,https://upsconline.nic.in,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
40,641da92514dabcb9,Union Public Service Commission,Name of Examination: National Defence Academy ...,NaN,NaN,NaN,NaN,NaN,NaN,https://upsconline.nic.in,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
41,2cf5fdf3defabc1d,Union Public Service Commission,Name of Examination: National Defence Academy ...,NaN,NaN,NaN,NaN,NaN,NaN,https://upsconline.nic.in,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
42,7241f7cedfba8318,Union Public Service Commission,Name of Examination: National Defence Academy ...,NaN,NaN,NaN,NaN,NaN,NaN,https://upsconline.nic.in,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13

In [49]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 43 non-null     str
 1   organization       43 non-null     str
 2   exam_name          43 non-null     str
 3   post               0 non-null      float64
 4   vacancies          0 non-null      float64
 5   notification_date  12 non-null     str
 6   application_start  0 non-null      float64
 7   last_date          12 non-null     str
 8   exam_date          12 non-null     str
 9   application_url    43 non-null     str
 10  notification_url   43 non-null     str
 11  source             43 non-null     str
 12  status             43 non-null     str
 13  last_checked       43 non-null     str
dtypes: float64(3), str(11)
memory usage: 4.8 KB

In [50]:
df.head()

,id,organization,exam_name,post,vacancies,notification_date,application_start,last_date,exam_date,application_url,notification_url,source,status,last_checked
0,49c89ad78681cd7f,Staff Selection Commission,ASO Grade Limited Departmental Competitive Exa...,NaN,NaN,2026-03-16,NaN,2026-04-07,2026-05-01,https://ssc.gov.in,https://ssc.gov.in/api/attachment/uploads/mast...,SSC,Upcoming,2026-10-13
1,3eb35f4b4e78c1c8,Staff Selection Commission,"Combined Graduate Level Examination, 2026",NaN,NaN,2026-03-01,NaN,2026-04-01,May – June 2026,https://ssc.gov.in,https://ssc.gov.in/api/attachment/uploads/mast...,SSC,Upcoming,2026-10-13
2,937c761766e5e1ed,Staff Selection Commission,Combined Higher Secondary (10+2) Level Examina...,NaN,NaN,2026-04-01,NaN,2026-05-01,July – September 2026,https://ssc.gov.in,https://ssc.gov.in/api/attachment/uploads/mast...,SSC,Upcoming,2026-10-13
3,cb98754822e27ca7,Staff Selection Commission,"Combined Hindi Translators Examination, 2026",NaN,NaN,2026-04-01,NaN,2026-05-01,August – September 2026,https://ssc.gov.in,https://ssc.gov.in/api/attachment/uploads/mast...,SSC,Upcoming,2026-10-13
4,04e6554cb154a5f4,Staff Selection Commission,Constables (GD) in Central Armed Police Forces...,NaN,NaN,2026-09-01,NaN,2026-10-01,January – March 2027,https://ssc.gov.in,https://ssc.gov.in/api/attachment/uploads/mast...,SSC,Upcoming,2026-10-13

In [51]:
df=df.drop(columns=['id','post','vacancies','application_start','application_url'])

In [52]:
df

,organization,exam_name,notification_date,last_date,exam_date,notification_url,source,status,last_checked
0,Staff Selection Commission,ASO Grade Limited Departmental Competitive Exa...,2026-03-16,2026-04-07,2026-05-01,https://ssc.gov.in/api/attachment/uploads/mast...,SSC,Upcoming,2026-10-13
1,Staff Selection Commission,"Combined Graduate Level Examination, 2026",2026-03-01,2026-04-01,May – June 2026,https://ssc.gov.in/api/attachment/uploads/mast...,SSC,Upcoming,2026-10-13
2,Staff Selection Commission,Combined Higher Secondary (10+2) Level Examina...,2026-04-01,2026-05-01,July – September 2026,https://ssc.gov.in/api/attachment/uploads/mast...,SSC,Upcoming,2026-10-13
3,Staff Selection Commission,"Combined Hindi Translators Examination, 2026",2026-04-01,2026-05-01,August – September 2026,https://ssc.gov.in/api/attachment/uploads/mast...,SSC,Upcoming,2026-10-13
4,Staff Selection Commission,Constables (GD) in Central Armed Police Forces...,2026-09-01,2026-10-01,January – March 2027,https://ssc.gov.in/api/attachment/uploads/mast...,SSC,Upcoming,2026-10-13
5,Staff Selection Commission,JSA / LDC Grade Limited Departmental Competiti...,2026-03-16,2026-04-07,2026-05-01,https://ssc.gov.in/api/attachment/uploads/mast...,SSC,Upcoming,2026-10-13
6,Staff Selection Commission,"Junior Engineer (Civil, Mechanical & Electrica...",2026-03-01,2026-04-01,May – June 2026,https://ssc.gov.in/api/attachment/uploads/mast...,SSC,Upcoming,2026-10-13
7,Staff Selection Commission,Multi-Tasking (Non- Technical) Staff & Havalda...,2026-06-01,2026-07-01,September – November 2026,https://ssc.gov.in/api/attachment/uploads/mast...,SSC,Upcoming,2026-10-13
8,Staff Selection Commission,SSA / UDC Grade Limited Departmental Competiti...,2026-03-16,2026-04-07,2026-05-01,https://ssc.gov.in/api/attachment/uploads/mast...,SSC,Upcoming,2026-10-13
9,Staff Selection Commission,"Selection Post Examination, Phase-XIV, 2026",2026-03-01,2026-04-01,May – July 2026,https://ssc.gov.in/api/attachment/uploads/mast...,SSC,Upcoming,2026-10-13
10,Staff Selection Commission,"Stenographer Grade ‘C’ & ‘D’ Examination, 2026",2026-04-01,2026-05-01,August – September 2026,https://ssc.gov.in/api/attachment/uploads/mast...,SSC,Upcoming,2026-10-13
11,Staff Selection Commission,Sub-Inspector in Delhi Police & Central Armed ...,2026-05-01,2026-06-01,October – November 2026,https://ssc.gov.in/api/attachment/uploads/mast...,SSC,Upcoming,2026-10-13
12,Union Public Service Commission,Date / (s) of Examination,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
13,Union Public Service Commission,Duration of Examination,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
14,Union Public Service Commission,Examination,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
15,Union Public Service Commission,Forthcoming Examinations,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
16,Union Public Service Commission,Name of Examination,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
17,Union Public Service Commission,Name of Examination: CISF AC(EXE) LDCE-2025,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
18,Union Public Service Commission,Name of Examination: CISF AC(EXE) LDCE-2026,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
19,Union Public Service Commission,Name of Examination: Central Armed Police Forc...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
20,Union Public Service Commission,Name of Examination: Central Armed Police Forc...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
21,Union Public Service Commission,Name of Examination: Civil Services (Prelimina...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
22,Union Public Service Commission,Name of Examination: Civil Services (Prelimina...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
23,Union Public Service Commission,Name of Examination: Combined Defence Services...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
24,Union Public Service Commission,Name of Examination: Combined Defence Services...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
25,Union Public Service Commission,Name of Examination: Combined Defence Services...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
26,Union Public Service Commission,Name of Examination: Combined Defence Services...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
27,Union Public Service Commission,Name of Examination: Combined Geo-Scientist (P...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
28,Union Public Service Commission,Name of Examination: Combined Geo-Scientist (P...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
29,Union Public Service Commission,Name of Examination: Combined Medical Services...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
30,Union Public Service Commission,Name of Examination: Combined Medical Services...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
31,Union Public Service Commission,Name of Examination: Combined Section Officer ...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
32,Union Public Service Commission,Name of Examination: Combined Section Officers...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
33,Union Public Service Commission,Name of Examination: Engineering Services (Pre...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
34,Union Public Service Commission,Name of Examination: Engineering Services (Pre...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
35,Union Public Service Commission,Name of Examination: Indian Economic Service -...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
36,Union Public Service Commission,Name of Examination: Indian Economic Service -...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
37,Union Public Service Commission,Name of Examination: Indian Forest Service (Pr...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
38,Union Public Service Commission,Name of Examination: Indian Forest Service (Pr...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
39,Union Public Service Commission,Name of Examination: National Defence Academy ...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
40,Union Public Service Commission,Name of Examination: National Defence Academy ...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
41,Union Public Service Commission,Name of Examination: National Defence Academy ...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
42,Union Public Service Commission,Name of Examination: National Defence Academy ...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13

In [53]:
df.rename(columns=lambda x: x.title().replace("_"," "), inplace=True)

In [54]:
df

,Organization,Exam Name,Notification Date,Last Date,Exam Date,Notification Url,Source,Status,Last Checked
0,Staff Selection Commission,ASO Grade Limited Departmental Competitive Exa...,2026-03-16,2026-04-07,2026-05-01,https://ssc.gov.in/api/attachment/uploads/mast...,SSC,Upcoming,2026-10-13
1,Staff Selection Commission,"Combined Graduate Level Examination, 2026",2026-03-01,2026-04-01,May – June 2026,https://ssc.gov.in/api/attachment/uploads/mast...,SSC,Upcoming,2026-10-13
2,Staff Selection Commission,Combined Higher Secondary (10+2) Level Examina...,2026-04-01,2026-05-01,July – September 2026,https://ssc.gov.in/api/attachment/uploads/mast...,SSC,Upcoming,2026-10-13
3,Staff Selection Commission,"Combined Hindi Translators Examination, 2026",2026-04-01,2026-05-01,August – September 2026,https://ssc.gov.in/api/attachment/uploads/mast...,SSC,Upcoming,2026-10-13
4,Staff Selection Commission,Constables (GD) in Central Armed Police Forces...,2026-09-01,2026-10-01,January – March 2027,https://ssc.gov.in/api/attachment/uploads/mast...,SSC,Upcoming,2026-10-13
5,Staff Selection Commission,JSA / LDC Grade Limited Departmental Competiti...,2026-03-16,2026-04-07,2026-05-01,https://ssc.gov.in/api/attachment/uploads/mast...,SSC,Upcoming,2026-10-13
6,Staff Selection Commission,"Junior Engineer (Civil, Mechanical & Electrica...",2026-03-01,2026-04-01,May – June 2026,https://ssc.gov.in/api/attachment/uploads/mast...,SSC,Upcoming,2026-10-13
7,Staff Selection Commission,Multi-Tasking (Non- Technical) Staff & Havalda...,2026-06-01,2026-07-01,September – November 2026,https://ssc.gov.in/api/attachment/uploads/mast...,SSC,Upcoming,2026-10-13
8,Staff Selection Commission,SSA / UDC Grade Limited Departmental Competiti...,2026-03-16,2026-04-07,2026-05-01,https://ssc.gov.in/api/attachment/uploads/mast...,SSC,Upcoming,2026-10-13
9,Staff Selection Commission,"Selection Post Examination, Phase-XIV, 2026",2026-03-01,2026-04-01,May – July 2026,https://ssc.gov.in/api/attachment/uploads/mast...,SSC,Upcoming,2026-10-13
10,Staff Selection Commission,"Stenographer Grade ‘C’ & ‘D’ Examination, 2026",2026-04-01,2026-05-01,August – September 2026,https://ssc.gov.in/api/attachment/uploads/mast...,SSC,Upcoming,2026-10-13
11,Staff Selection Commission,Sub-Inspector in Delhi Police & Central Armed ...,2026-05-01,2026-06-01,October – November 2026,https://ssc.gov.in/api/attachment/uploads/mast...,SSC,Upcoming,2026-10-13
12,Union Public Service Commission,Date / (s) of Examination,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
13,Union Public Service Commission,Duration of Examination,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
14,Union Public Service Commission,Examination,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
15,Union Public Service Commission,Forthcoming Examinations,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
16,Union Public Service Commission,Name of Examination,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
17,Union Public Service Commission,Name of Examination: CISF AC(EXE) LDCE-2025,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
18,Union Public Service Commission,Name of Examination: CISF AC(EXE) LDCE-2026,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
19,Union Public Service Commission,Name of Examination: Central Armed Police Forc...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
20,Union Public Service Commission,Name of Examination: Central Armed Police Forc...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
21,Union Public Service Commission,Name of Examination: Civil Services (Prelimina...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
22,Union Public Service Commission,Name of Examination: Civil Services (Prelimina...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
23,Union Public Service Commission,Name of Examination: Combined Defence Services...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
24,Union Public Service Commission,Name of Examination: Combined Defence Services...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
25,Union Public Service Commission,Name of Examination: Combined Defence Services...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
26,Union Public Service Commission,Name of Examination: Combined Defence Services...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
27,Union Public Service Commission,Name of Examination: Combined Geo-Scientist (P...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
28,Union Public Service Commission,Name of Examination: Combined Geo-Scientist (P...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
29,Union Public Service Commission,Name of Examination: Combined Medical Services...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
30,Union Public Service Commission,Name of Examination: Combined Medical Services...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
31,Union Public Service Commission,Name of Examination: Combined Section Officer ...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
32,Union Public Service Commission,Name of Examination: Combined Section Officers...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
33,Union Public Service Commission,Name of Examination: Engineering Services (Pre...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
34,Union Public Service Commission,Name of Examination: Engineering Services (Pre...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
35,Union Public Service Commission,Name of Examination: Indian Economic Service -...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
36,Union Public Service Commission,Name of Examination: Indian Economic Service -...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
37,Union Public Service Commission,Name of Examination: Indian Forest Service (Pr...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
38,Union Public Service Commission,Name of Examination: Indian Forest Service (Pr...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
39,Union Public Service Commission,Name of Examination: National Defence Academy ...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
40,Union Public Service Commission,Name of Examination: National Defence Academy ...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
41,Union Public Service Commission,Name of Examination: National Defence Academy ...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
42,Union Public Service Commission,Name of Examination: National Defence Academy ...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13

In [55]:
df.rename(columns={'Notification Date':'Uploading Date'},inplace=True)

In [56]:
df

,Organization,Exam Name,Uploading Date,Last Date,Exam Date,Notification Url,Source,Status,Last Checked
0,Staff Selection Commission,ASO Grade Limited Departmental Competitive Exa...,2026-03-16,2026-04-07,2026-05-01,https://ssc.gov.in/api/attachment/uploads/mast...,SSC,Upcoming,2026-10-13
1,Staff Selection Commission,"Combined Graduate Level Examination, 2026",2026-03-01,2026-04-01,May – June 2026,https://ssc.gov.in/api/attachment/uploads/mast...,SSC,Upcoming,2026-10-13
2,Staff Selection Commission,Combined Higher Secondary (10+2) Level Examina...,2026-04-01,2026-05-01,July – September 2026,https://ssc.gov.in/api/attachment/uploads/mast...,SSC,Upcoming,2026-10-13
3,Staff Selection Commission,"Combined Hindi Translators Examination, 2026",2026-04-01,2026-05-01,August – September 2026,https://ssc.gov.in/api/attachment/uploads/mast...,SSC,Upcoming,2026-10-13
4,Staff Selection Commission,Constables (GD) in Central Armed Police Forces...,2026-09-01,2026-10-01,January – March 2027,https://ssc.gov.in/api/attachment/uploads/mast...,SSC,Upcoming,2026-10-13
5,Staff Selection Commission,JSA / LDC Grade Limited Departmental Competiti...,2026-03-16,2026-04-07,2026-05-01,https://ssc.gov.in/api/attachment/uploads/mast...,SSC,Upcoming,2026-10-13
6,Staff Selection Commission,"Junior Engineer (Civil, Mechanical & Electrica...",2026-03-01,2026-04-01,May – June 2026,https://ssc.gov.in/api/attachment/uploads/mast...,SSC,Upcoming,2026-10-13
7,Staff Selection Commission,Multi-Tasking (Non- Technical) Staff & Havalda...,2026-06-01,2026-07-01,September – November 2026,https://ssc.gov.in/api/attachment/uploads/mast...,SSC,Upcoming,2026-10-13
8,Staff Selection Commission,SSA / UDC Grade Limited Departmental Competiti...,2026-03-16,2026-04-07,2026-05-01,https://ssc.gov.in/api/attachment/uploads/mast...,SSC,Upcoming,2026-10-13
9,Staff Selection Commission,"Selection Post Examination, Phase-XIV, 2026",2026-03-01,2026-04-01,May – July 2026,https://ssc.gov.in/api/attachment/uploads/mast...,SSC,Upcoming,2026-10-13
10,Staff Selection Commission,"Stenographer Grade ‘C’ & ‘D’ Examination, 2026",2026-04-01,2026-05-01,August – September 2026,https://ssc.gov.in/api/attachment/uploads/mast...,SSC,Upcoming,2026-10-13
11,Staff Selection Commission,Sub-Inspector in Delhi Police & Central Armed ...,2026-05-01,2026-06-01,October – November 2026,https://ssc.gov.in/api/attachment/uploads/mast...,SSC,Upcoming,2026-10-13
12,Union Public Service Commission,Date / (s) of Examination,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
13,Union Public Service Commission,Duration of Examination,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
14,Union Public Service Commission,Examination,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
15,Union Public Service Commission,Forthcoming Examinations,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
16,Union Public Service Commission,Name of Examination,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
17,Union Public Service Commission,Name of Examination: CISF AC(EXE) LDCE-2025,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
18,Union Public Service Commission,Name of Examination: CISF AC(EXE) LDCE-2026,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
19,Union Public Service Commission,Name of Examination: Central Armed Police Forc...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
20,Union Public Service Commission,Name of Examination: Central Armed Police Forc...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
21,Union Public Service Commission,Name of Examination: Civil Services (Prelimina...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
22,Union Public Service Commission,Name of Examination: Civil Services (Prelimina...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
23,Union Public Service Commission,Name of Examination: Combined Defence Services...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
24,Union Public Service Commission,Name of Examination: Combined Defence Services...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
25,Union Public Service Commission,Name of Examination: Combined Defence Services...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
26,Union Public Service Commission,Name of Examination: Combined Defence Services...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
27,Union Public Service Commission,Name of Examination: Combined Geo-Scientist (P...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
28,Union Public Service Commission,Name of Examination: Combined Geo-Scientist (P...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
29,Union Public Service Commission,Name of Examination: Combined Medical Services...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
30,Union Public Service Commission,Name of Examination: Combined Medical Services...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
31,Union Public Service Commission,Name of Examination: Combined Section Officer ...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
32,Union Public Service Commission,Name of Examination: Combined Section Officers...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
33,Union Public Service Commission,Name of Examination: Engineering Services (Pre...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
34,Union Public Service Commission,Name of Examination: Engineering Services (Pre...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
35,Union Public Service Commission,Name of Examination: Indian Economic Service -...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
36,Union Public Service Commission,Name of Examination: Indian Economic Service -...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
37,Union Public Service Commission,Name of Examination: Indian Forest Service (Pr...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
38,Union Public Service Commission,Name of Examination: Indian Forest Service (Pr...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
39,Union Public Service Commission,Name of Examination: National Defence Academy ...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
40,Union Public Service Commission,Name of Examination: National Defence Academy ...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
41,Union Public Service Commission,Name of Examination: National Defence Academy ...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13
42,Union Public Service Commission,Name of Examination: National Defence Academy ...,NaN,NaN,NaN,https://www.upsc.gov.in/exams-related-info/exa...,UPSC,Published,2026-10-13

In [57]:
df.to_csv('filtered_data.csv', index=True)