## This is jupiter notebook in VS code

In [3]:
pip install pandas

Requirement already satisfied: pandas in .\.venv\Lib\site-packages (3.0.6)
Requirement already satisfied: numpy>=2.3.3 in .\.venv\Lib\site-packages (from pandas) (2.5.4)
Requirement already satisfied: python-dateutil>=2.8.2 in .\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\.venv\Lib\site-packages (from pandas) (2026.5)
Requirement already satisfied: six>=1.5 in .\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
import pandas as pd 
df=pd.read_csv("youtube_2025_1.csv")
print (df)

           Youtuber Name  Total Videos
0             Eric Patel            68
1     Cynthia Harrington           128
2          Amanda Walker           282
3      Jessica Nelson MD           302
4        Matthew Sherman           129
...                  ...           ...
4995       Jasmine Smith           106
4996      John Rasmussen           130
4997          Lisa Burke           179
4998          Steve Diaz           182
4999         Austin Tate            92

[5000 rows x 2 columns]

In [5]:
type (df)

pandas.DataFrame

In [6]:
df=pd.read_csv('youtube_2025_1.csv',index_col='Youtuber Name')
df

                    Total Videos
Youtuber Name
Eric Patel                    68
Cynthia Harrington           128
Amanda Walker                282
Jessica Nelson MD            302
Matthew Sherman              129
...                          ...
Jasmine Smith                106
John Rasmussen               130
Lisa Burke                   179
Steve Diaz                   182
Austin Tate                   92

[5000 rows x 1 columns]

In [7]:
df.values

array([[ 68],
       [128],
       [282],
       ...,
       [179],
       [182],
       [ 92]], shape=(5000, 1))

In [8]:
df

                    Total Videos
Youtuber Name
Eric Patel                    68
Cynthia Harrington           128
Amanda Walker                282
Jessica Nelson MD            302
Matthew Sherman              129
...                          ...
Jasmine Smith                106
John Rasmussen               130
Lisa Burke                   179
Steve Diaz                   182
Austin Tate                   92

[5000 rows x 1 columns]

In [9]:
df.index

Index(['Eric Patel', 'Cynthia Harrington', 'Amanda Walker',
       'Jessica Nelson MD', 'Matthew Sherman', 'Anna Berry', 'Richard Arnold',
       'Stephanie Potter', 'Teresa Aguirre', 'Anne Adkins',
       ...
       'Erin Bradley', 'Brooke Perez', 'Nicholas Jordan', 'Howard Phelps',
       'Sharon Graham', 'Jasmine Smith', 'John Rasmussen', 'Lisa Burke',
       'Steve Diaz', 'Austin Tate'],
      dtype='str', name='Youtuber Name', length=5000)

In [10]:
df1=pd.read_csv('youtube_2025_1.csv').squeeze('columns')
print(df1)

           Youtuber Name  Total Videos
0             Eric Patel            68
1     Cynthia Harrington           128
2          Amanda Walker           282
3      Jessica Nelson MD           302
4        Matthew Sherman           129
...                  ...           ...
4995       Jasmine Smith           106
4996      John Rasmussen           130
4997          Lisa Burke           179
4998          Steve Diaz           182
4999         Austin Tate            92

[5000 rows x 2 columns]

In [11]:
type(df1)

pandas.DataFrame

In [12]:
import pandas as pd

df = pd.read_csv("youtube_2025_1.csv")

series = df["Youtuber Name"]

print(series)
print(type(series))

0               Eric Patel
1       Cynthia Harrington
2            Amanda Walker
3        Jessica Nelson MD
4          Matthew Sherman
               ...
4995         Jasmine Smith
4996        John Rasmussen
4997            Lisa Burke
4998            Steve Diaz
4999           Austin Tate
Name: Youtuber Name, Length: 5000, dtype: str
<class 'pandas.Series'>

In [13]:
df

           Youtuber Name  Total Videos
0             Eric Patel            68
1     Cynthia Harrington           128
2          Amanda Walker           282
3      Jessica Nelson MD           302
4        Matthew Sherman           129
...                  ...           ...
4995       Jasmine Smith           106
4996      John Rasmussen           130
4997          Lisa Burke           179
4998          Steve Diaz           182
4999         Austin Tate            92

[5000 rows x 2 columns]

In [14]:
dataframe=pd.read_csv('youtube_2025_1.csv',index_col='Youtuber Name').squeeze('columns')

In [15]:
df1.values

array([['Eric Patel', 68],
       ['Cynthia Harrington', 128],
       ['Amanda Walker', 282],
       ...,
       ['Lisa Burke', 179],
       ['Steve Diaz', 182],
       ['Austin Tate', 92]], shape=(5000, 2), dtype=object)

In [16]:
dataframe.values

array([ 68, 128, 282, ..., 179, 182,  92], shape=(5000,))

In [17]:
dataframe.index

Index(['Eric Patel', 'Cynthia Harrington', 'Amanda Walker',
       'Jessica Nelson MD', 'Matthew Sherman', 'Anna Berry', 'Richard Arnold',
       'Stephanie Potter', 'Teresa Aguirre', 'Anne Adkins',
       ...
       'Erin Bradley', 'Brooke Perez', 'Nicholas Jordan', 'Howard Phelps',
       'Sharon Graham', 'Jasmine Smith', 'John Rasmussen', 'Lisa Burke',
       'Steve Diaz', 'Austin Tate'],
      dtype='str', name='Youtuber Name', length=5000)

In [18]:
dataframe.dtype

dtype('int64')

In [19]:
dataframe=dataframe.astype('int32')
dataframe

Youtuber Name
Eric Patel             68
Cynthia Harrington    128
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
                     ...
Jasmine Smith         106
John Rasmussen        130
Lisa Burke            179
Steve Diaz            182
Austin Tate            92
Name: Total Videos, Length: 5000, dtype: int32

In [20]:
dataframe.size

5000

In [21]:
dataframe.shape

(5000,)

In [22]:
dataframe.ndim

1

In [23]:
dataframe.name

'Total Videos'

In [24]:
dataframe.is_unique

False

In [25]:
df

           Youtuber Name  Total Videos
0             Eric Patel            68
1     Cynthia Harrington           128
2          Amanda Walker           282
3      Jessica Nelson MD           302
4        Matthew Sherman           129
...                  ...           ...
4995       Jasmine Smith           106
4996      John Rasmussen           130
4997          Lisa Burke           179
4998          Steve Diaz           182
4999         Austin Tate            92

[5000 rows x 2 columns]

In [26]:
df.head()

        Youtuber Name  Total Videos
0          Eric Patel            68
1  Cynthia Harrington           128
2       Amanda Walker           282
3   Jessica Nelson MD           302
4     Matthew Sherman           129

In [27]:
dataframe.head(10)

Youtuber Name
Eric Patel             68
Cynthia Harrington    128
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
Anna Berry             98
Richard Arnold        494
Stephanie Potter      133
Teresa Aguirre        316
Anne Adkins           140
Name: Total Videos, dtype: int32

In [28]:
dataframe.tail()

Youtuber Name
Jasmine Smith     106
John Rasmussen    130
Lisa Burke        179
Steve Diaz        182
Austin Tate        92
Name: Total Videos, dtype: int32

In [29]:
df.tail(10)

        Youtuber Name  Total Videos
4990     Erin Bradley           231
4991     Brooke Perez           273
4992  Nicholas Jordan           261
4993    Howard Phelps           126
4994    Sharon Graham           231
4995    Jasmine Smith           106
4996   John Rasmussen           130
4997       Lisa Burke           179
4998       Steve Diaz           182
4999      Austin Tate            92

In [30]:
dataframe.sample(10)

Youtuber Name
Michael Lee          163
Nathan Reeves        316
Matthew Andrews      143
Michelle Turner      477
Colton Bauer         113
Stacy Wheeler        132
James Jackson        488
Charles Robertson    328
Curtis Trevino       335
Nancy Wilkerson      472
Name: Total Videos, dtype: int32

In [31]:
youtube=pd.read_csv('youtube_2025_dataset_202504061614.csv')
avg=youtube['Avg Video Length (min)']
avg

0       24.8
1       22.9
2       24.0
3       24.6
4       24.6
        ...
4995    22.0
4996    26.3
4997    25.2
4998    24.5
4999    25.2
Name: Avg Video Length (min), Length: 5000, dtype: float64

In [32]:
type(avg)

pandas.Series

In [33]:
avg.value_counts()

Avg Video Length (min)
24.1    276
23.8    264
23.9    256
24.2    253
24.0    251
       ...
19.9      1
27.3      1
28.0      1
21.0      1
20.7      1
Name: count, Length: 78, dtype: int64

In [34]:
avg.sort_values()

500     19.1
451     19.3
1713    19.9
171     20.6
3704    20.7
        ...
2748    28.0
925     28.1
364     28.3
1467    28.4
361     28.9
Name: Avg Video Length (min), Length: 5000, dtype: float64

In [35]:
dataframe

Youtuber Name
Eric Patel             68
Cynthia Harrington    128
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
                     ...
Jasmine Smith         106
John Rasmussen        130
Lisa Burke            179
Steve Diaz            182
Austin Tate            92
Name: Total Videos, Length: 5000, dtype: int32

In [ ]:
dataframe.sort_values(ascending=False)#descending

Youtuber Name
Amy Russo            500
Eric Riley           500
David Santiago       500
Jeremiah Freeman     500
Dominique Martin     500
                    ...
Brittany Gross        50
Allison Dougherty     50
Michael Pena          50
Ronald Williams       50
Christy Hernandez     50
Name: Total Videos, Length: 5000, dtype: int32

#### Method Chaining

In [41]:
avg.sort_values(ascending=False).head(1)

361    28.9
Name: Avg Video Length (min), dtype: float64

In [40]:
avg.sort_values(ascending=False).head(1).values[0]

np.float64(28.9)

In [42]:
avg

0       24.8
1       22.9
2       24.0
3       24.6
4       24.6
        ...
4995    22.0
4996    26.3
4997    25.2
4998    24.5
4999    25.2
Name: Avg Video Length (min), Length: 5000, dtype: float64

In [43]:
avg.sort_values(inplace=True)

In [44]:
avg

500     19.1
451     19.3
1713    19.9
171     20.6
3704    20.7
        ...
2748    28.0
925     28.1
364     28.3
1467    28.4
361     28.9
Name: Avg Video Length (min), Length: 5000, dtype: float64

In [47]:
dataframe

Youtuber Name
Eric Patel             68
Cynthia Harrington    128
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
                     ...
Jasmine Smith         106
John Rasmussen        130
Lisa Burke            179
Steve Diaz            182
Austin Tate            92
Name: Total Videos, Length: 5000, dtype: int32

In [46]:
dataframe.sort_index()

Youtuber Name
Aaron Archer        136
Aaron Bishop        151
Aaron Brown          51
Aaron Burns         314
Aaron Carrillo      210
                   ...
Zachary Phillips    478
Zachary Russell      81
Zachary Shelton     446
Zoe Peterson         78
Zoe Smith            83
Name: Total Videos, Length: 5000, dtype: int32