## This is jupiter notebook in VS code

In [47]:
pip install pandas

Requirement already satisfied: pandas in .\.venv\Lib\site-packages (3.0.6)
Requirement already satisfied: numpy>=2.3.3 in .\.venv\Lib\site-packages (from pandas) (2.5.4)
Requirement already satisfied: python-dateutil>=2.8.2 in .\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\.venv\Lib\site-packages (from pandas) (2026.5)
Requirement already satisfied: six>=1.5 in .\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [48]:
import pandas as pd 
df=pd.read_csv("youtube_2025_1.csv")
print (df)

           Youtuber Name  Total Videos
0             Eric Patel            68
1     Cynthia Harrington           128
2          Amanda Walker           282
3      Jessica Nelson MD           302
4        Matthew Sherman           129
...                  ...           ...
4995       Jasmine Smith           106
4996      John Rasmussen           130
4997          Lisa Burke           179
4998          Steve Diaz           182
4999         Austin Tate            92

[5000 rows x 2 columns]

In [49]:
type (df)

pandas.DataFrame

In [50]:
df=pd.read_csv('youtube_2025_1.csv',index_col='Youtuber Name')
df

                    Total Videos
Youtuber Name
Eric Patel                    68
Cynthia Harrington           128
Amanda Walker                282
Jessica Nelson MD            302
Matthew Sherman              129
...                          ...
Jasmine Smith                106
John Rasmussen               130
Lisa Burke                   179
Steve Diaz                   182
Austin Tate                   92

[5000 rows x 1 columns]

In [51]:
df.values

array([[ 68],
       [128],
       [282],
       ...,
       [179],
       [182],
       [ 92]], shape=(5000, 1))

In [52]:
df

                    Total Videos
Youtuber Name
Eric Patel                    68
Cynthia Harrington           128
Amanda Walker                282
Jessica Nelson MD            302
Matthew Sherman              129
...                          ...
Jasmine Smith                106
John Rasmussen               130
Lisa Burke                   179
Steve Diaz                   182
Austin Tate                   92

[5000 rows x 1 columns]

In [53]:
df.index

Index(['Eric Patel', 'Cynthia Harrington', 'Amanda Walker',
       'Jessica Nelson MD', 'Matthew Sherman', 'Anna Berry', 'Richard Arnold',
       'Stephanie Potter', 'Teresa Aguirre', 'Anne Adkins',
       ...
       'Erin Bradley', 'Brooke Perez', 'Nicholas Jordan', 'Howard Phelps',
       'Sharon Graham', 'Jasmine Smith', 'John Rasmussen', 'Lisa Burke',
       'Steve Diaz', 'Austin Tate'],
      dtype='str', name='Youtuber Name', length=5000)

In [54]:
df1=pd.read_csv('youtube_2025_1.csv').squeeze('columns')
print(df1)

           Youtuber Name  Total Videos
0             Eric Patel            68
1     Cynthia Harrington           128
2          Amanda Walker           282
3      Jessica Nelson MD           302
4        Matthew Sherman           129
...                  ...           ...
4995       Jasmine Smith           106
4996      John Rasmussen           130
4997          Lisa Burke           179
4998          Steve Diaz           182
4999         Austin Tate            92

[5000 rows x 2 columns]

In [55]:
type(df1)

pandas.DataFrame

In [56]:
import pandas as pd

df = pd.read_csv("youtube_2025_1.csv")

series = df["Youtuber Name"]

print(series)
print(type(series))

0               Eric Patel
1       Cynthia Harrington
2            Amanda Walker
3        Jessica Nelson MD
4          Matthew Sherman
               ...
4995         Jasmine Smith
4996        John Rasmussen
4997            Lisa Burke
4998            Steve Diaz
4999           Austin Tate
Name: Youtuber Name, Length: 5000, dtype: str
<class 'pandas.Series'>

In [57]:
df

           Youtuber Name  Total Videos
0             Eric Patel            68
1     Cynthia Harrington           128
2          Amanda Walker           282
3      Jessica Nelson MD           302
4        Matthew Sherman           129
...                  ...           ...
4995       Jasmine Smith           106
4996      John Rasmussen           130
4997          Lisa Burke           179
4998          Steve Diaz           182
4999         Austin Tate            92

[5000 rows x 2 columns]

In [58]:
dataframe=pd.read_csv('youtube_2025_1.csv',index_col='Youtuber Name').squeeze('columns')

In [59]:
df1.values

array([['Eric Patel', 68],
       ['Cynthia Harrington', 128],
       ['Amanda Walker', 282],
       ...,
       ['Lisa Burke', 179],
       ['Steve Diaz', 182],
       ['Austin Tate', 92]], shape=(5000, 2), dtype=object)

In [60]:
dataframe.values

array([ 68, 128, 282, ..., 179, 182,  92], shape=(5000,))

In [61]:
dataframe.index

Index(['Eric Patel', 'Cynthia Harrington', 'Amanda Walker',
       'Jessica Nelson MD', 'Matthew Sherman', 'Anna Berry', 'Richard Arnold',
       'Stephanie Potter', 'Teresa Aguirre', 'Anne Adkins',
       ...
       'Erin Bradley', 'Brooke Perez', 'Nicholas Jordan', 'Howard Phelps',
       'Sharon Graham', 'Jasmine Smith', 'John Rasmussen', 'Lisa Burke',
       'Steve Diaz', 'Austin Tate'],
      dtype='str', name='Youtuber Name', length=5000)

In [62]:
dataframe.dtype

dtype('int64')

In [64]:
dataframe=dataframe.astype('int32')
dataframe

Youtuber Name
Eric Patel             68
Cynthia Harrington    128
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
                     ...
Jasmine Smith         106
John Rasmussen        130
Lisa Burke            179
Steve Diaz            182
Austin Tate            92
Name: Total Videos, Length: 5000, dtype: int32

In [65]:
dataframe.size

5000

In [66]:
dataframe.shape

(5000,)

In [67]:
dataframe.ndim

1

In [ ]:
dataframe.name

'Total Videos'

In [70]:
dataframe.is_unique

False

In [71]:
df

           Youtuber Name  Total Videos
0             Eric Patel            68
1     Cynthia Harrington           128
2          Amanda Walker           282
3      Jessica Nelson MD           302
4        Matthew Sherman           129
...                  ...           ...
4995       Jasmine Smith           106
4996      John Rasmussen           130
4997          Lisa Burke           179
4998          Steve Diaz           182
4999         Austin Tate            92

[5000 rows x 2 columns]

In [72]:
df.head()

        Youtuber Name  Total Videos
0          Eric Patel            68
1  Cynthia Harrington           128
2       Amanda Walker           282
3   Jessica Nelson MD           302
4     Matthew Sherman           129

In [74]:
dataframe.head(10)

Youtuber Name
Eric Patel             68
Cynthia Harrington    128
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
Anna Berry             98
Richard Arnold        494
Stephanie Potter      133
Teresa Aguirre        316
Anne Adkins           140
Name: Total Videos, dtype: int32